services:
  - type: web
    name: ig-telegram-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
    healthCheckPath: /health
